(function(){String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s*(\S*(?:\s+\S+)*)\s*$/,"$1")});String.prototype.capitalize||(String.prototype.capitalize=function(){return this.charAt(0).toUpperCase()+this.slice(1)});String.prototype.startsWith||(String.prototype.startsWith=function(c){return 0===this.indexOf(c)});String.prototype.endsWith||(String.prototype.endsWith=function(c){return-1!==this.indexOf(c,this.length-c.length)});String.prototype.csvarray||(String.prototype.csvarray=
function(){return this&&this.trim()?this.split(","):[]});String.prototype.csvcontains||(String.prototype.csvcontains=function(c){return this.endsWith(c)||0<=this.indexOf(c+",")?!0:!1});String.prototype.csvappend||(String.prototype.csvappend=function(c){var a;(a=(this||"").trim())&&(a+=",");return a+c});String.prototype.csvremove||(String.prototype.csvremove=function(c){var a,b,d=this;a=d.indexOf(c+",");0<=a?(b=d.slice(0,a),d=b+=d.slice(a+c.length+1)):d.endsWith(","+c)?d=d.slice(0,-1*(c.length+1)):
d===c&&(d="");return d});Array.prototype.indexOf||(Array.prototype.indexOf=function(c){var a;if(null===this)throw new TypeError;for(a=0;a<this.length;a+=1)if(this[a]===c)return a;return-1});Array.prototype.shuffle||(Array.prototype.shuffle=function(){var c,a,b;for(c=this.length-1;0<c;c-=1)a=Math.floor(Math.random()*(c+1)),b=this[c],this[c]=this[a],this[a]=b;return this});Date.prototype.toISOString||(Date.prototype.toISOString=function(){function c(a){return 10>a?"0"+a:a}return this.getUTCFullYear()+
"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z"})})();
var jtminjsDecorateWithUtilities=function(c){c.byId=function(a){return document.getElementById(a)};c.isAvailable=function(a,b){return a&&/^(?:function|object|unknown)$/.test(typeof a[b])};c.log=function(a){try{console&&console.log&&console.log(a)}catch(b){}};c.err=function(a){alert(a)};c.assert=function(a){if(!a)throw c.err("An application integrity check has failed. Please reload the page in your browser."),"uo.assert";};c.out=function(a,b){var d=c.byId(a);d?d.innerHTML=b:c.log("DOM id "+a+" not available for output")};
c.prefixed=function(a,b){return a&&0===a.indexOf(b)?!0:!1};c.ellipsis=function(a,b){if(!a||"string"!==typeof a)return"";a=a.trim();return a.length<=b?a:a=a.slice(0,b-3)+"..."};c.safestr=function(a){return!a?"":String(a)};c.safeint=function(a){a||(a=0);"number"!==typeof a&&(a=parseInt(a,10));return a};c.safeget=function(a,b){var d=c.byId(a);if(d)return d[b]};c.saferef=function(a,b){var c,e;if(!a)return null;c=b.split(".?");for(e=0;e<c.length;e+=1)if(a&&a[c[e]])a=a[c[e]];else return null;return a};
c.enc=function(a){a=a||"";"string"===typeof a&&(a=a.trim());return encodeURIComponent(a)};c.dec=function(a){a=a||"";"string"===typeof a&&(a=a.trim());try{a=decodeURIComponent(a)}catch(b){c.log("decodeURIComponent failure: "+b)}return a};c.embenc=function(a){a=c.enc(a);return a=a.replace(/'/g,"%27")};c.dquotenc=function(a){a=c.enc(a);return a=a.replace(/"/g,"&quot;")};c.ndq=function(a){return!a?"":a=a.replace(/"/g,"&quot;")};c.canonize=function(a){a=(a||"").replace(/\s/g,"");a=a.replace(/\"/g,"");
a=a.replace(/\./g,"");a=a.replace(/\:/g,"");a=a.replace(/\//g,"");a=a.replace(/\?/g,"");a=a.replace(/\#/g,"");a=a.replace(/\[/g,"");a=a.replace(/\]/g,"");a=a.replace(/\@/g,"");a=a.replace(/\!/g,"");a=a.replace(/\$/g,"");a=a.replace(/\&/g,"");a=a.replace(/\'/g,"");a=a.replace(/\(/g,"");a=a.replace(/\)/g,"");a=a.replace(/\*/g,"");a=a.replace(/\+/g,"");a=a.replace(/\,/g,"");a=a.replace(/\;/g,"");a=a.replace(/\=/g,"");return a=a.toLowerCase()};c.ISOString2Day=function(a){var b,c;if(!a)return new Date;
b=parseInt(a.slice(0,4),10);c=parseInt(a.slice(5,7),10);a=parseInt(a.slice(8,10),10);return new Date(b,c-1,a,0,0,0,0)};c.colloquialDate=function(a,b){var d=new Date,e,g;"string"===typeof a&&(a=c.ISOString2Day(a));d=d.getTime()-a.getTime();if(864E5>d)return"Today";if(1728E5>d)return"Yesterday";e=String("Sunday Monday Tuesday Wednesday Thursday Friday Saturday Sunday".split(" ")[a.getUTCDay()]);g=String("January February March April May June July August September October November December".split(" ")[a.getMonth()]);
b&&(e=e.slice(0,3),g=g.slice(0,3));e=e+" "+g+" "+String(a.getUTCDate());31536E6<d&&(e+=" "+String(a.getFullYear()));return e};c.isProbablyEmail=function(a){return a&&a.match(/^\S+@\S+\.\S+$/)};c.paramsToObj=function(a,b,c){var e,g;e=a.indexOf("?");0<=e&&(a=a.slice(e+1));b||(b={});if(a){a=a.split("&");for(e=0;e<a.length;e+=1)g=a[e].split("="),1<g.length?b[g[0]]="String"===c?String(g[1]):g[1]:b.anchor=g[0]}return b};c.parseParams=function(a){var b,d={};b=window.location.hash;0===b.indexOf("#")&&(b=
b.slice(1));c.paramsToObj(b,d,a);b=window.location.search;c.paramsToObj(b,d,a);return d};c.objdata=function(a,b){var d="",e;if(!a)return"";b||(b=[]);for(e in a)a.hasOwnProperty(e)&&0>b.indexOf(e)&&(d&&(d+="&"),d+=e+"="+c.enc(a[e]));return d};c.paramsToFormInputs=function(a){var b="",c,e;if(!a)return"";a=a.split("&");for(c=0;c<a.length;c+=1)e=a[c].split("="),b+='<input type="hidden" name="'+e[0]+'" value="'+e[1]+'"/>';return b};c.makelink=function(a){var b="";if(!a)return"";/[\.\,\)]$/.test(a)&&(b=
a.slice(-1),a=a.slice(0,-1));return'<a href="'+a+'" onclick="window.open(\''+a+"');return false;\">"+a+"</a>"+b};c.linkify=function(a){if(!a)return"";a=a.replace(/https?:\S+/g,function(a){return c.makelink(a)});return a=a.replace(/\n/g,"<br/>")};c.isLowFuncBrowser=function(){var a;return navigator&&(a=navigator,0<=a.userAgent.indexOf("Firefox")||0<=a.userAgent.indexOf("Chrome")||0<=a.userAgent.indexOf("Safari")&&0>a.userAgent.indexOf("CyanogenMod")&&0>a.userAgent.indexOf("Android"))?!1:!0};c.on=function(a,
b,d){"string"===typeof a&&(a=c.byId(a));c.isAvailable(a,"addEventListener")?a.addEventListener(b,d,!1):c.isAvailable(a,"attachEvent")&&(a["e"+b+d]=d,a[b+d]=function(){a["e"+b+d](window.event)},a.attachEvent("on"+b,a[b+d]))};c.off=function(a,b,d){"string"===typeof a&&(a=c.byId(a));c.isAvailable(a,"removeEventListener")?a.removeEventListener(b,d,!1):c.isAvailable(a,"detachEvent")&&a.detachEvent("on"+b,a[b+d])};c.evtend=function(a){a&&(a.preventDefault?a.preventDefault():a.returnValue=!1,a.stopPropagation?
a.stopPropagation():a.cancelBubble=!0)};c.fs=function(a){a&&(a=c.safestr(a).trim(),0>a.indexOf(")")&&(a+="()"),a.indexOf(";")<a.length-1&&(a+=";"),0>a.indexOf("return false")&&(a+="return false;"));return c.fsd(a)};c.fsd=function(a){return a};c.isHTMLElement=function(a){if("string"!==typeof a)return!1;a=c.safestr(a).trim().toLowerCase();return 0<="a abbr acronym address applet area article aside audio b base basefont bdi bdo big blockquote body br button canvas caption center cite code col colgroup command datalist dd del details dfn dialog dir div dl dt em embed fieldset figcaption figure font footer form frame frameset h1 h2 h3 h4 h5 h6 head header hr html i iframe img input ins kbd keygen label legend li link map mark menu meta meter nav noframes noscript object ol optgroup option output p param pre progress q rp rt ruby s samp script section select small source span strike strong style sub summary sup table tbody td textarea tfoot th thead time title tr track tt u ul var video wbr".split(" ").indexOf(a)?
!0:!1};c.isHTMLVoidElement=function(a){a=c.safestr(a).trim().toLowerCase();return 0<="area base br col command embed hr img input keygen link menuitem meta param source track wbr".split(" ").indexOf(a)?!0:!1};c.toru=function(a,b){if(a)return b||a};c.tacattr=function(a){switch(a){case "cla":return"class";case "fo":return"for"}return a};c.tac2html=function(a,b){var d;b||(b={html:"",elemtype:null,attrobj:null,content:null,isHTMLTag:!1,i:null});if("object"!==typeof a||!a.length)return c.safestr(a);if(0===
a.length)return"";b.elemtype=a[0];b.isHTMLTag=c.isHTMLElement(b.elemtype);if(b.isHTMLTag){b.html+="<"+b.elemtype;if(1<a.length)if(b.attrobj=a[1],b.attrobj&&"object"===typeof b.attrobj&&!b.attrobj.length)for(d in b.attrobj)b.attrobj.hasOwnProperty(d)&&(void 0!==b.attrobj[d]&&null!==b.attrobj[d])&&(b.html+=" "+c.tacattr(d)+'="'+b.attrobj[d]+'"');else b.attrobj&&(b.content=b.attrobj);if(c.isHTMLVoidElement(b.elemtype))return b.html+=" />",b.html;b.html+=">";!b.content&&2<a.length&&(b.content=a[2]);b.content&&
(b.html+=c.tac2html(b.content));b.html+="</"+b.elemtype+">";return b.html}for(b.i=0;b.i<a.length;b.i+=1)b.html+=c.tac2html(a[b.i]);return b.html};c.localDelayBusyWait=function(){var a,b;if(document&&window&&window.location&&window.location.href&&!(0>window.location.href.indexOf("localhost:8080"))){a=c.byId("localDelayBusyWaitDiv");a||(a=document.createElement("div"),a.id="localDelayBusyWaitDiv",document.body.appendChild(a));for(a=b=(new Date).getTime();300>a-b;)a=(new Date).getTime(),c.out("localDelayBusyWaitDiv",
"delay "+(a-b));c.out("localDelayBusyWaitDiv","")}};c.semaphores={};c.semaphore=function(a){c.semaphore[a]||(c.semaphore[a]={});return c.semaphore[a]};c.request=function(a,b,d,e,g,h,k,f){h&&"processing"===h.critsec?(c.log(a+" "+b+" already in progress..."),setTimeout(function(){c.log(a+" "+b+" retry...");c.request(a,b,d,e,g,h,k,f)},200)):(h&&(h.critsec="processing"),k&&k(a,b,d,h),c.localDelayBusyWait&&c.localDelayBusyWait(),f=f||0,function(a,b,c,d,e,g,h){var f=new XMLHttpRequest;f.open(a,b);f.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");f.timeout=h;f.onreadystatechange=function(){4===f.readyState&&(g&&(g.critsec="completed"),200===f.status||0===f.status&&f.responseText?d(f.responseText):e&&e(f.status,f.responseText||f.statusText,a,b,c))};f.send(c)}(a,b,d,e,g,h,f))};c.call=function(a,b,d,e,g,h,k,f){var l=JSON||window.JSON;l||c.err("JSON not supported, please use a modern browser");c.request(a,b,d,function(f){if(f){try{f=l.parse(f)}catch(h){c.log("JSON parse failure: "+h),g(415,f,a,b,d)}e(f)}},
g,h,k,f)};c.cookie=function(a,b,c){var e;if(b||0>=c)b=b||"",c||(c=365),e=new Date,e.setDate(e.getDate()+c),b=escape(b)+"; expires="+e.toUTCString(),document.cookie=a+"="+b;b=document.cookie;c=b.indexOf(" "+a+"=");0>c&&(c=b.indexOf(a+"="));0>c?b=null:(b=b.slice(c),b=b.slice(b.indexOf("=")+1),c=b.indexOf(";"),0<=c&&(b=b.slice(0,c)),b=unescape(b));return b};c.geoPos=function(a,b){b||(b={h:a.offsetHeight,w:a.offsetWidth,x:0,y:0});b.x+=a.offsetLeft;b.y+=a.offsetTop;return a.offsetParent?c.geoPos(a.offsetParent,
b):b};c.geoXY=function(a){var b;if(a.pageX)return{x:a.pageX,y:a.pageY};b={h:-1,w:-1,x:a.offsetX,y:a.offsetY};(b=c.geoPos(a.srcElement,b))||(b={x:a.offsetX,y:a.offsetY});return b};c.loadAppModules=function(a,b,d,e,g){var h,k,f;d.lastIndexOf(".")>d.lastIndexOf("/")&&(d=d.slice(0,d.lastIndexOf("/")));"/"!==d.charAt(d.length-1)&&(d+="/");g=g||"";for(h=0;h<b.length;h+=1)k=d+b[h]+".js"+g,f=b[h],0<=f.indexOf("/")&&(f=f.slice(f.lastIndexOf("/")+1),b[h]=f),a[f]||(f=document.createElement("script"),f.async=
!0,f.src=k,document.body.appendChild(f));c.waitForModules(a,b,e)};c.waitForModules=function(a,b,d){var e,g,h=!0;for(e=0;e<b.length;e+=1)if(g=b[e],!a[g]){h=!1;break}h?d():setTimeout(function(){c.waitForModules(a,b,d)},100)}};
